### ISSUE TITLE
Protocol Data

### ISSUE THREAD

**Issue by nobu-sh** [PrismarineJS/bedrock-protocol#111]
I was curious where is the protocol data sourced from that protodef utilizes? 
I was writing my own implementations using protodef on a personal project using the data on this repo and I realized protodef is unable to parse packets correctly if the information is not up to date 100% I suppose. 

EG: I was trying to parse a resource_packs_info packet and it kept throwing an error saying it was not the expected length. Come to find out the proto yml was not up to date. 

If something were to update would I need to update the yml's manually and convert it to json or how does this function? It is not well outlined.

**Comment by extremeheat** [comment]
The issue with the resource pack packet should have been fixed in the latest release, are you sure that's still an issue? This was also recently patched [in gophertunnel](https://github.com/Sandertv/gophertunnel/commit/f35fb7fdf7603bb78aa199dd59dec644e328a95f).

You can see the CONTRIBUTING.md file https://github.com/PrismarineJS/bedrock-protocol/blob/master/CONTRIBUTING.md for the info you want regarding how the protocol.json is generated. It's transformed to JSON from a combination of types.yml and proto.yml files, which also have protocol documentation inside of them. A visual editor for the YML files is available [here](https://extremeheat.github.io/protodef-yaml/editor/).

**Comment by nobu-sh** [comment]
okay, thank you this is very helpful.
It was fixed I was just curious on how I could go about fixing it myself on the off-chance this project stops being worked on over time.
