### ISSUE TITLE
1.1 Support

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/bedrock-protocol#23]
- [ ] NBT (this has been on hold for a while in [#15](https://github.com/PrismarineJS/prismarine-nbt/issues/15) but needs to be done, https://github.com/PrismarineJS/prismarine-nbt)
- [ ] Protocol changes (?)
- [ ] Stability, see below
- [ ] Update examples to reflect protocol changes

This library is terribly unpredictable, before we merge **anything** [#9](https://github.com/mhsjlw/node-raknet/issues/9) in node-raknet must be fixed. This way we can finally fix up encryption (to be honest, I'm probably going to rewrite it as a native extension... it's a little slow)

Goals:
- [ ] Be able to maintain a session with a player and be able to finish login handshake and world sending 99% of the time, rather than 50/50 right now
- [ ] Potentially support EDU edition and Code Blocks websockets see [PEWS](https://github.com/jocopa3/PEWS-API), just for fun :smile:

Work has begun in the 1.1 branch

**Comment by rom1504** [comment]
@mhsjlw @filfat where is the most recent source of MCPE protocol ?
looks like minet died.

**Comment by rom1504** [comment]
ah https://github.com/kennyvv/MiNET-1.2

**Comment by rom1504** [comment]
https://github.com/kennyvv/MiNET-1.2/blob/1.2/src/MiNET/MiNET/Net/MCPE%20Protocol%20Documentation.md

**Comment by ghost** [comment]
We can just steal from PocketMine as well: https://github.com/pmmp/PocketMine-MP

**Comment by SuperOP535** [comment]
Is this project still alive? Does it work for MCPE 1.2.2?

**Comment by ghost** [comment]
1.2.2 is not supported at this time

**Comment by geekytime** [comment]
I'd like to help. How close did you get on the 1.1 branch? Should I use that as the jumping off point for adding 1.2.2 support?

**Comment by ghost** [comment]
Yes. Please join https://gitter.im/mhsjlw/pocket-minecraft-protocol if you'd like a run down of how we do things (ex. how everything works in the big picture)

**Comment by extremeheat** [comment]
Took another look at node-raknet and have some findings:

* pong is supposed to have two fields: client timestamp and server timestamp both u64
* ACK, NACK packets and queues aren't implemented 
* no recovery queue to resend lost packets to the client 
* no packet ordering (required for Minecraft since the encryption is dependent on the last packet)
* periodic ping packets aren't sent
* no MTU size tests - client is supposed to try max MTU size and constantly send connection requests with lower MTU sizes until the server responds and agrees to an MTU size (looks like mc works for current MTU but minet doesn't since it hard codes a smaller number that it will reply to)
* NewIncommingConnection packet is broken (not sure if it's a field related issue or side effect of a problem above)

**Comment by rom1504** [comment]
Yeah not surprised by those. Feel free to fix if you want. Using the other implementation you have is also ok.
Do you want to open a PR for the update for pocket-minecraft-protocol btw ?
So we have a place to talk about it

**Comment by extremeheat** [comment]
Yeah I can open a PR for discussion. What branch should it be on? I branched off of 1.1 but can change it to master

**Comment by rom1504** [comment]
Yeah just put it on master

**Comment by rom1504** [comment]
moved to https://github.com/PrismarineJS/pocket-minecraft-protocol/issues/34
