### ISSUE TITLE
Protodef yaml ?

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/bedrock-protocol#51]
I saw https://github.com/extremeheat/protodef-yaml and I'm wondering whether it's really worth it. It feels like what was done for protodefc.
It makes it possible to use a format that's slightly easier to use for humans but that is both harder to parser and to generate for computers.
Using such yaml files as the reference in minecraft data would make it harder for users in other languages (we have a few now) to use the files.

Keeping both the yaml and the json would mean we can't edit the json file so contributors have to know both the yaml and json formats.

Do you think it's really important / useful to use that yaml format rather than json ? And if yes what would be the future of it ?

**Comment by extremeheat** [comment]
If it's a burden in the future, the exit plan is simple, we can just delete the yaml. 

Couple of problems I wanted to solve with the new format:
* make it more condensed (less whitespace) for easier scrolling and readability
* make it easier to write and maintain - minus the comments, the protocol.json is about 7k loc vs 2.5k for the yaml
* add comments (one of most important imo)
* make it easy to generate docs and type definitions (this should bring more meaning)
* we can extend later on if needed

The yml isn't really designed for others to parse, it's designed to be turned to JSON before being used anywhere, `npx protodef-yaml input.yml output.json`. Like a file for a preprocessor instead of a compiler. We don't need to put the yaml in mc-data as the intended users are humans. For updating the code we can ask people to use the generator here, the only problem I had was was how (or if) to deal with older versions.

As it currently stands I think the yml files are simple enough to read and write and I use them as protocol documentation also. So hopefully it's not too big of a burden, but we can wait and see how adoption goes. 

For this project, being able to quickly comment things out and back in in the yml makes it alot easier to debug as there's not really a good wiki.vg for bedrock.

Especially for big packets, having things like `or` statements is a nice feature, part of why people usually just write up the protocol in code:
https://github.com/PrismarineJS/bedrock-protocol/blob/master/data/latest/types.yaml#L444
https://github.com/PrismarineJS/bedrock-protocol/blob/master/data/1.16.201/protocol.json#L1163

**Comment by rom1504** [comment]
ok, I think it adds some complexity I'm not sure we can't afford, but I can see your points. Let's keep it for now and revisit in the future

**Comment by rom1504** [comment]
Let's close this for now
