### ISSUE TITLE
Packaging track

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/bedrock-protocol#65]
On the packaging track:
* createServer
* Check if readme is ok
* Move protocol.json to minecraft data
* Remove unneeded dependencies from package.json (ie bedrock provider)
* Check whatever else doesn't belong here and either put in a subfolder in example, either put in another prismarine repo
* Put on npm
* Use it in mineflayer

I will keep updating this as it get better

Final objective : PrismarineJs packages have support for bedrock as good as mcpc (without duplicating packages)

**Comment by extremeheat** [comment]
* server and readme updated 
* Need to investigate moving protocol further, currently the js is pre-compiled instead of generated + evaled at runtime for easier debugging.  So moving the protocol things + generator tool would mean it’d have to interop with the protocol lib somehow 
* Moving chunk data to pchunk needs native support, so need to remove the mapping logic and add blocks and items data to mc-data. Interim solution could be to require bedrock-provider there for now
* for Mineflayer I think the easiest approach is to have separate set of plugins but expose the same api. Only complex thing here is the inventories, there needs to be a higher level API than the current clicks (eg to move, swap, pickup, place, etc instead of clicking windows).

**Comment by rom1504** [comment]
I'm going to close this (as initial objective is 90% done) in favor of #116
