### ISSUE TITLE
Support clients and client encryption

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/bedrock-protocol#7]
have a look at http://www.pingx.net/freenode/mcpedevs/2015/7/22/2

**Comment by rom1504** [comment]
needed to connect as a different identify than mine

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/createServer.js#L236

**Comment by rom1504** [comment]
I guess the client id and device id need to be options in createClient

**Comment by ghost** [comment]
As of 0.15, this is no longer needed. We just need to generate a `randomId` and figure out how to obtain a XUID (Xbox Live user identification)

**Comment by rom1504** [comment]
This is still kind of needed for multi-version (including 0.14) support ;)

**Comment by ghost** [comment]
Note the 'As of 0.15' :wink:, but yes, we still need to generate these ids for 0.14

**Comment by ghost** [comment]
Due to the nature of Minecraft: PE's update system it may seem that multi-version support really isn't going to be useful. I'm referring to the fact that when an update comes out, everyone automatically updates on the Google Play store or App Store making older versions very uncommon and not worth supporting

**Comment by ghost** [comment]
Oops, I didn't mean to close. This is going to be required for 0.15 on wards

**Comment by ghost** [comment]
I'm going to hijack this issue and change the topic to just client support in general

**Comment by rom1504** [comment]
unvalid
